version: '3.1'

services:
  api:
    container_name: feather-api
    build: .
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:feather123@db:5432/feather_app
      FLASK_APP: feather_simple_api
      FLASK_RUN_HOST: 0.0.0.0
      RATELIMIT_STORAGE_URL: redis://redis:6379
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
    command: ["./scripts/wait-for-it.sh", "db:5432", "--", "./scripts/entrypoint.sh"]

  db:
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: feather123
    ports:
      - "5500:5432"
    volumes:
      - './db/init:/docker-entrypoint-initdb.d/'
  
  redis:
    image: redis:6.0.9-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: