"""Initial migration.

Revision ID: c3000867dcd5
Revises:
Create Date: 2020-12-08 21:10:10.697528

"""
from alembic import op
import sqlalchemy as sa
from feather_simple_api.extensions.flask_sqlalchemy.guid_type import GUID


# revision identifiers, used by Alembic.
revision = "c3000867dcd5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "id", GUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("firstname", sa.String(length=120), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column(
            "occupation",
            sa.Enum("employed", "student", "self_employed", name="occupationstatus"),
            nullable=True,
        ),
        sa.Column("has_child", sa.Boolean(), nullable=True),
        sa.Column("child_num", sa.Integer(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
